spring:
  application:
    name: course
  datasource:
    url: jdbc:mysql://course-db:3306/courses?createDatabaseIfNotExist=true
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8071