eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://students:8070
          predicates:
            - Path=/api/students/**
        - id: courses
          uri: http://courses:8071
          predicates:
            - Path=/api/courses/**

management:
  endpoints:
    web:
      exposure:
        include: "*"